<a href="https://colab.research.google.com/github/estebanvz/alura-deep-learning-2/blob/clase02/Aula01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librerias

In [44]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
np.set_printoptions(precision=2, suppress=True)

# Dataset y Normalización

In [45]:
dataset = keras.datasets.fashion_mnist
((img_entrenamiento, etiquetas_entrenamiento),(img_test, etiquetas_test)) = dataset.load_data()
img_entrenamiento = img_entrenamiento/255.0
img_test = img_test/255.0
img_entrenamiento.shape, img_test.shape

((60000, 28, 28), (10000, 28, 28))

# Cargar Modelo

In [46]:
modelo_caro = keras.models.load_model("/content/drive/MyDrive/alura/deep_learning_2/modelo_inicial_caro.h5")

In [47]:
modelo_caro.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_10 (Flatten)        (None, 784)               0         
                                                                 
 dense_20 (Dense)            (None, 50)                39250     
                                                                 
 dropout (Dropout)           (None, 50)                0         
                                                                 
 dense_21 (Dense)            (None, 50)                2550      
                                                                 
 dropout_1 (Dropout)         (None, 50)                0         
                                                                 
 dense_22 (Dense)            (None, 10)                510       
                                                                 
Total params: 42,310
Trainable params: 42,310
Non-tra

## Modelo Tiny

In [66]:
tiny = keras.Sequential()
tiny.add(keras.layers.Input(3,))
tiny.add(keras.layers.Dense(2,))

In [72]:
tiny.predict([[0.5,0.3,0.2]])

array([[-0.03, -0.02]], dtype=float32)

In [68]:
tiny.layers[0].get_weights()

[array([[ 0.04,  0.67],
        [ 0.09, -0.69],
        [-0.4 , -0.73]], dtype=float32), array([0., 0.], dtype=float32)]

In [69]:
tiny.layers[0].get_weights()[0].shape

(3, 2)

In [70]:
np.dot( [0.5,0.3,0.2] ,tiny.layers[0].get_weights()[0])

array([-0.03, -0.02])

In [71]:
[0.5,0.3,0.2] @ tiny.layers[0].get_weights()[0]

array([-0.03, -0.02])