<a href="https://colab.research.google.com/github/estebanvz/alura-deep-learning-2/blob/clase04/Aula02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librerias

In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
np.set_printoptions(precision=2, suppress=True)

# Dataset y Normalización

In [ ]:
dataset = keras.datasets.fashion_mnist
((img_entrenamiento, etiquetas_entrenamiento),(img_test, etiquetas_test)) = dataset.load_data()
img_entrenamiento = img_entrenamiento/255.0
img_test = img_test/255.0
img_entrenamiento.shape, img_test.shape

4431872/4422102 [==============================] - 0s 0us/step


((60000, 28, 28), (10000, 28, 28))

# Cargar Modelo

In [ ]:
modelo_caro = keras.models.load_model("/content/drive/MyDrive/alura/deep_learning_2/modelo_inicial_caro.h5")

In [ ]:
modelo_caro.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_10 (Flatten)        (None, 784)               0         
                                                                 
 dense_20 (Dense)            (None, 50)                39250     
                                                                 
 dropout (Dropout)           (None, 50)                0         
                                                                 
 dense_21 (Dense)            (None, 50)                2550      
                                                                 
 dropout_1 (Dropout)         (None, 50)                0         
                                                                 
 dense_22 (Dense)            (None, 10)                510       
                                                                 
Total params: 42,310
Trainable params: 42,310
Non-tra

## Modelo Tiny

In [ ]:
tiny = keras.Sequential()
tiny.add(keras.layers.Input(3,))
tiny.add(keras.layers.Dense(3,))
tiny.add(keras.layers.Dense(2,))
tiny.predict(np.array([[0.5,0.3,0.2]]))

array([[-0.74,  0.16]], dtype=float32)

In [ ]:
tiny.layers[0].get_weights()[0].shape

(3, 3)

In [ ]:
tiny.layers[1].get_weights()[0].shape

(3, 2)

In [ ]:
([0.5,0.3,0.2] @ tiny.layers[0].get_weights()[0]) @ tiny.layers[1].get_weights()[0]

array([-0.74,  0.16])

In [ ]:
tiny.layers[1].get_weights()

[array([[-0.87, -0.72],
        [ 0.91, -1.08],
        [-0.84,  0.03]], dtype=float32), array([0., 0.], dtype=float32)]

# Bias

In [ ]:
tiny.layers[0].get_weights()[1]

array([0., 0., 0.], dtype=float32)

In [ ]:
tiny.layers[1].get_weights()[1]

array([0., 0.], dtype=float32)

In [ ]:
tiny.layers[0].get_config()

{'activation': 'linear',
 'activity_regularizer': None,
 'bias_constraint': None,
 'bias_initializer': {'class_name': 'Zeros', 'config': {}},
 'bias_regularizer': None,
 'dtype': 'float32',
 'kernel_constraint': None,
 'kernel_initializer': {'class_name': 'GlorotUniform',
  'config': {'seed': None}},
 'kernel_regularizer': None,
 'name': 'dense',
 'trainable': True,
 'units': 3,
 'use_bias': True}